version: "3.8"
services:
    api:
        build:
            context: ./backend
        networks:
            - net
    
    client:
        build: 
            context: ./frontend
        environment:
            - DANGEROUSLY_DISABLE_HOST_CHECK=true
        networks:
            - net

    nginx:
        restart: always
        build:
            context: ./nginx
        
        env_file:
            - ./.env
        ports:
            - "${APP_PORT}:80"
        networks:
            - net

networks:
  net: