version: "3.8"
services:
    api:
        restart: always
        build:
            context: ./backend
        image: api:${IMAGE_TAG}
        env_file:
            - ./.env
        networks:
            - net
    
    client:
        restart: always
        build: 
            context: ./frontend
        image: client:${IMAGE_TAG}
        env_file:
            - ./.env
        networks:
            - net

    nginx:
        restart: always
        build:
            context: ./nginx
        
        env_file:
            - ./.env
        ports:
            - "${APP_PORT}:80"
        networks:
            - net

networks:
  net: